import { createElement } from 'lwc';
import Chart from 'c/chart';

describe('c-chart', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-chart', {
            is: Chart
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const linechart = element.shadowRoot.querySelector('canvas.linechart');
        expect(linechart).not.toBe(null);
    });
});